### ISSUE TITLE
Incompatible with rich >= 13.0.0

### ISSUE THREAD

**Issue by hassec** [ewels/rich-codex#45]
I've found that installing `rich-codex` as a dev dependency is not possible as my package uses a recent version of `rich` but `rich-codex` requires `rich<13.0.0`. 

This constraint arises from the dependency on `rich-cli` which specifies `rich = "^12.4.0"`. 

Maybe `rich-cli` could be made an optional dependency or the `rich-cli` could loosen its requirements to `rich > 12.4.0`?

**Comment by ewels** [comment]
Huh, that's annoying. Thanks for letting me know 👍🏻 

I think that the easiest solution is to just remove the dependency on `rich-cli` entirely. It's not actually used in the codebase at all, it's only there because I expected people to find it useful:

https://github.com/ewels/rich-codex/blob/eb967919edd7b95d20867180cfc4c565ab0a0cde/docs/inputs/markdown.md?plain=1#L22

I think it can be safely removed..

**Comment by ewels** [comment]
Ok, I've removed `rich-cli` from the dependencies and pushed this out in release [v1.2.7](https://github.com/ewels/rich-codex/releases/tag/v1.2.7). Thanks for reporting @hassec! Let me know if you hit any issues.

**Comment by ewels** [comment]
By the way, I'm always curious to know what people are using rich-codex for - let me know if it's something you can share! 😄

**Comment by ewels** [comment]
Great! Thanks, sounds cool 😁

**Comment by maxrake** [comment]
@ewels Thank you for the quick response on this issue...it helps me out as well!

Unfortunately, it appears the v1.2.7 release [did not successfully deploy to PyPI](https://github.com/ewels/rich-codex/actions/runs/7553943155/job/20565784212). From what I can tell, it appears the package was built as v1.2.6 instead of v1.2.7 and then the upload failed due to the file/version already existing there. Maybe the deploy workflow triggered before the version was updated somehow?

Is it possible to manually upload the v1.2.7 package to PyPI for this release so it can be available more broadly? Thanks again for the continued effort on this project! I recommend it to other developers.

**Comment by ewels** [comment]
ah oops, I forgot to update `__version__` in the scripts 🤦🏻‍♂️ 

Look the other way for a moment, I'll delete the release and try again 😅

**Comment by ewels** [comment]
ok, that did the job - should be there now: https://pypi.org/project/rich-codex/1.2.7/#history

Thanks for letting me know!
